name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_page:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GEMINI_TTS folder with copy of index.html
        run: |
          mkdir -p GEMINI_TTS
          cp index.html GEMINI_TTS/index.html
          cp favicon.ico GEMINI_TTS/favicon.ico

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
